import { BaseMessage } from '@langchain/core/messages';
import { Annotation } from '@langchain/langgraph';

/**
 * Defines the state that flows through our Multi-Agent Graph.
 * 
 * - messages: The conversation history (prompts, tool calls, tool results).
 * - tenantId: The tenant this investigation is scoped to.
 * - query: The original user question.
 * - evidence: The raw JSON findings collected by the Investigator Agent.
 * - finalReport: The formatted JSON report generated by the Reporter Agent.
 */
export const InvestigationStateAnnotation = Annotation.Root({
  messages: Annotation<BaseMessage[]>({
    reducer: (x, y) => x.concat(y),
    default: () => [],
  }),
  tenantId: Annotation<string>(),
  query: Annotation<string>(),
  evidence: Annotation<any[]>({
    reducer: (x, y) => x.concat(y),
    default: () => [],
  }),
  finalReport: Annotation<any>({
    reducer: (x, y) => y, // The last update replaces the previous one
    default: () => null,
  })
});

export type InvestigationState = typeof InvestigationStateAnnotation.State;
